var GAME_LEVELS = [
  ["                                                                                    +  ",
   "                        +                                          +                   ",
   "   +            +                                                         +            ",
   "                                                     +                                 ",
   "                       +                                                               ",
   "                                                                               +       ",
   "            +                                  o                 o                     ",
   "                                                    xx      xx                         ",
   "                +                    o o      xx                 xx    o            ~ x",
   "                                                  +                    xx           xxx",
   "       +                           xxxxx                     +                 xxxxxxxx",
   "                                                                             xxxxxxxxxx",
   "xxxx                                      o o            +      +             xxxxxxxxx",
   "xxx                     o                                                 xxxxxxxxxxxxx",
   "xxx                                      xxxxx       +       +            !!!xxxxxxxxxx",
   "xxx          xxxx    o  o      +         !!!!x                            !!!xxxxxxxxxx",
   "xxx  @       x!!x    x                   !!!!x                     xxxxx  !!!xxxxxxxxxx",
   "xxxxxxxxxxxxxx!!xxx     xxxxxxx!!!xxxxxxx!!!!!xxxxxxxx!!!!!xxxxxxxxxxxxxxx!!!xxxxxxxxxx",
   "xxxxxxxxxxxxxx!!xxx!!!!!xxxxxxx!!!xxxxxxx!!!!!xxxxxxxx!!!!!xxxxxxxxxxxxxxx!!!xxxxxxxxxx",
   "xxxxxxxxxxxxxx!!!!x!!!!!xxxxxxx!!!xxxxxxx!!!!!xxxxxxxx!!!!!xxxxxxxxxxxxxxx!!!xxxxxxxxxx",
   "xxxxxxxxxxxxxx!!!!!!!!!!xxxxxxx!!!xxxxxxx!!!!!xxxxxxxx!!!!!xxxxxxxxxxxxxxx!!!xxxxxxxxxx",
   "xxxxxxxxxxxxxx!!!!!!!!!!xxxxxxxx!xxxxxxxx!!!!!xxxxxxxxxx!xxxxxxxxxxxxxxxxx!!!xxxxxxxxxx",
   "xxxxxxxxxxxxxx!!!!!!!!!!xxxxxxxx!xxxxxxxxxx!!!xxxxxxxxxx!xxxxxxxxxxxxxxxxx!!!xxxxxxxxxx",
   "xxxxxxxxxxxxxx!!!!!!!!!!xxxxxxxx!xxxxxxxxxxx!!xxxxxxxxxx!xxxxxxxxxxxxxxxxxx!!xxxxxxxxxx"],
  ["                                      x!!x                                                                   x!x  ",
   "                                      x!!x                                                                   x!x  ",
   "                                      x!!x     oo                               =                            x!x  ",
   "                                      xx!!!!xxxxxxxx                                                         x!x  ",
   "                                       xxxvxxxxxx!!x                                              o   o   o  x!x  ",
   "                                                xx!x     x         o   o                                    xx!x  ",
   "                                                 x!x         =                                xxxxxxxxxxxxxxx!!x  ",
   "   =                                   =         xvxxxxxxxxxxx     x   x                        !!!!!!!!!!!!!!xx  ",
   "                        o                            xxxxxxxxxx  |   |   |  xx            xxxxxxxxxxxxxvxxxxxxx   ",
   "                     xxxxxx                          xxxxxxxxxxx!!!!!!!!!!!xxx           v                        ",
   "                     xxxxxx                               xxxxxxxxx!!!!!xxxxxx                                    ",
   "                                   o                      xxxxxxxxxxxxvxxxxxxx                               ~    ",
   "                                  xxx                                              x             xx         xxx   ",
   "                                                                    =              x            !!!!!!!!!!!!!!!!!!",
   "                         xx                   x      o                            xxx        xxx!!!!!!!!!!!!!!!!!!",
   "                                              xx     x                             x         x!!!!!!!!!!!!!!!!!!!!",
   "                                                            o  o         x         x         x!!!!!!!!!!!!!!!!!!!!",
   "               xx!!!xx       xxx    xxx                                  x         x         x!!!!!!!!!!!!!!!!!!!!",
   "              xx!!!!!xx             x                      xxxxxx        x   xxxxxxxxx       x!!!!!!!!!!!!!!!!!!!!",
   "             xx!!!!!!!xx          o x                x                   x   x               x!!!!!!!!!!!!!!!!!!!!",
   "     @       x!!!!!!!!!x            x                x                   x   x               x!!!!!!!!!!!!!!!!!!!!",
   "    xxx      x!!!!!!!!!x            x                x                   xxxxx               x!!!!!!!!!!!!!!!!!!!!",
   "    x x      x!!!!!!!!!x       x  o xx          o    x                      o                x!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xx     xx!!!!!!!xx     x!!!!!!!!!!           =       x         x!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxx      x!!!!!!!xx!     xxxxxxxxxxxxxxx   o o  xx!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x    o                 xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!x       xx!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x                     xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                            x!!!!!!!!!!!x!!!!!!x                                                              ",
   "                            x!!!!!v!!!!!x xxvxxx                                                              ",
   "                            xxxxxx xxxxxx                                                                     ",
   "                                                            =                                                 ",
   "                                                                                                              ",
   "                                                                                             o                ",
   "                                                                                            xxx               ",
   "             =                   o                                                  o                         ",
   "                               xxxxx                                               xxx                        ",
   "                              x!!!!!x                                                                         ",
   "    =                        x!!!!!!!!x                                    o                                  ",
   "                            xxx!!!!!!xxx                                  xxx                                 ",
   "                              x!!!!!!x                                                                        ",
   "  o                           x!!!!!!x                             o                                          ",
   "xxxx                          x!!!!!!x                           xxxx                                         ",
   "                    xxx       x!!!!!!x                    o                                                   ",
   "                    x         x!!!!!!x     o             xx                                                   ",
   "                    x         x!!!!!!x                                                           ~            ",
   "                    x         x!!!!!!x                                                                        ",
   "xxx      @          x         x!!!!!!x    x!!x    x!!!!x    x!!!!x    xx!!!xx       =            x!!!!!!!!!xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!x!!!!x!!xxxxxxxx!xxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "             x      x     xxx      xx   xx      xx   x  xx     x     xx      xx      xx                       ",
   "              x    x    xx   xx    xx   xx      xx   x  xx     x     xxx     xx      xx                       ",
   "               x  x     xx   xx    xx   xx      xx   x  xx     x     xx x    xx      xx                       ",
   "                x       xx   xx    xx   xx      xx   x  xx     x     xx  x   xx      xx                       ",
   "                x       xx   xx    xx   xx      xx   x  xx     x     xx   x  xx      xx                       ",
   "                x       xx   xx    xx   xx      xx   x  xx     x     xx    x xx      xx                       ",
   "                x       xx   xx    xx   xx      xx   x  xx     x     xx     xxx      xx                       ",
   "                x         xxx        xxx          xxxxxxx      x     xx      xx                               ",
   "                                                                                     xx                       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
